services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    network_mode: host
    volumes:
      - ./workdir:/opt/adguardhome/work
      - ./confdir:/opt/adguardhome/conf
    restart: unless-stopped
